stop-words = "stopwords.txt"
prefix = "."
dataset = "movies_whole"
corpus = "line.toml"
index = "idx"
[query-runner]
	query-id-start = 1
	query-path = "movies-queries.txt"
[[analyzers]]
	filter = "default-unigram-chain"
	method = "ngram-word"
	ngram = 1
