prefix = "."
stop-words = "stopwords.txt"

dataset = "movies"
corpus = "line.toml"
index = "idx_names"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "movies-queries.txt"
query-id-start = 1
